# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

module "global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "global-lb-frontend"
  project_id    = "cosmic-talent-493214-v9"
  url_map_input = module.global-lb-backend.backend_service_info
}

module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v14.2.0"
  name       = "global-lb-backend"
  project_id = "cosmic-talent-493214-v9"

  serverless_neg_backends = [{
    region          = module.frontend-service.location
    service_name    = module.frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}

module "frontend-service" {
  source     = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id = "cosmic-talent-493214-v9"
  location   = "us-central1"

  service_name = "frontend-service"
  containers = [{
    container_image = "us-docker.pkg.dev/cloudrun/container/hello"
    container_name  = "service-container"
    env_vars        = { backend_service_SERVICE_ENDPOINT = module.backend-service.service_uri }
    ports           = { container_port = 8080 }
  }]

  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"

  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }

  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true

  service_scaling = {
    min_instance_count = 0
  }

  template_scaling = {
    min_instance_count = 0
  }
}

module "backend-service" {
  source     = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id = "cosmic-talent-493214-v9"
  location   = "us-central1"

  service_name = "backend-service"
  containers = [{
    container_image  = "us-docker.pkg.dev/cloudrun/container/hello"
    container_name   = "service-container"
    env_secret_vars  = merge({ cloudsql_secret_SECRET = module.cloudsql-secret.env_vars.SECRET }, { db_password_secret_SECRET = module.db-password-secret.env_vars.SECRET })
    env_vars         = { cloudsql_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME = module.cloudsql-postgresql.instance_connection_name, cloudsql_postgresql_CLOUD_SQL_DATABASE_HOST = module.cloudsql-postgresql.instance_first_ip_address, cloudsql_postgresql_CLOUD_SQL_DATABASE_NAME = module.cloudsql-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME }
    ports            = { container_port = 8080 }
    volume_mounts    = [{ mount_path = "/cloudsql", name = "cloudsql" }]
  }]

  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_ONLY"

  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }

  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes = [{
    cloud_sql_instance = {
      instances = [module.cloudsql-postgresql.instance_connection_name]
    }
    name = "cloudsql"
  }]

  service_scaling = {
    min_instance_count = 0
  }

  template_scaling = {
    min_instance_count = 0
  }
}

module "cloudsql-postgresql" {
  source           = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id       = "cosmic-talent-493214-v9"
  name             = "cloudsql-postgresql"
  edition          = "ENTERPRISE_PLUS"
  database_version = "POSTGRES_15"
  availability_type = "REGIONAL"

  deletion_protection         = false
  deletion_protection_enabled = false
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  disk_autoresize             = true

  database_flags = [{
    name  = "cloudsql.iam_authentication"
    value = "on"
  }]

  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }

  iam_users = [{
    email = module.backend-service.service_account_id.email
    id    = module.backend-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
}

module "cloudsql-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "cosmic-talent-493214-v9"
  name        = "cloudsql-secret"
  secret_data = "VITE_API_BASE_URL"
}

module "db-password-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "cosmic-talent-493214-v9"
  name        = "db-password-secret"
  secret_data = module.cloudsql-postgresql.generated_user_password
}
