# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

output "global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.global-lb-frontend.external_ip
}

output "global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.global-lb-frontend.external_ipv6_address
}

output "global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.global-lb-frontend.ip_address_internal_managed_http
}

output "global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.global-lb-frontend.ip_address_internal_managed_https
}

output "frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-service.service_uri
}

output "backend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.backend-service.service_uri
}
