/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthWorkoutsRouteImport } from './routes/_auth/workouts'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthMealsRouteImport } from './routes/_auth/meals'
import { Route as AuthPlanningRouteImport } from './routes/_auth/planning'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkoutsRoute = AuthWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMealsRoute = AuthMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlanningRoute = AuthPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/meals': typeof AuthMealsRoute
  '/planning': typeof AuthPlanningRoute
  '/settings': typeof AuthSettingsRoute
  '/workouts': typeof AuthWorkoutsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/meals': typeof AuthMealsRoute
  '/planning': typeof AuthPlanningRoute
  '/settings': typeof AuthSettingsRoute
  '/workouts': typeof AuthWorkoutsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/meals': typeof AuthMealsRoute
  '/_auth/planning': typeof AuthPlanningRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/workouts': typeof AuthWorkoutsRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/meals' | '/planning' | '/settings' | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/meals' | '/planning' | '/settings' | '/workouts' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/meals'
    | '/_auth/planning'
    | '/_auth/settings'
    | '/_auth/workouts'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workouts': {
      id: '/_auth/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthWorkoutsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meals': {
      id: '/_auth/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthMealsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/planning': {
      id: '/_auth/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthPlanningRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMealsRoute: typeof AuthMealsRoute
  AuthPlanningRoute: typeof AuthPlanningRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthWorkoutsRoute: typeof AuthWorkoutsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMealsRoute: AuthMealsRoute,
  AuthPlanningRoute: AuthPlanningRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthWorkoutsRoute: AuthWorkoutsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
